name: Generate Podcast Feeds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3.5.3
    - name: Run Feed Generator
      uses: principecabrera/podcast-generator@main
